const ApiRoutes = {
  baseUrl: "https://qpay-project-managenent-production.up.railway.app",
  // baseUrl: "http://localhost:3000",
  login: "/admin/login",
  totalcounts: "/admin/report-count",
  addEmployee: "/employees/add",
  employeeList: "/employees/list",
  employeeDelete: "/employees/delete",
  employeeUpdate: "/employees/update",
  updateEmployeeStatus: "/employees/update-status",
  projectAdd: "/project/add",
  projectList: "/project/list",
  projectDelete: "/project/delete",
  projectUpdate: "/project/update",
  updateProjectStatus: "/project/update-status",
  projectModuleAdd: "/projectmodule/add",
  projectModuleList: "/projectmodule/list",
  projectModuleDelete: "/projectmodule/delete",
  projectModuleUpdate: "/projectmodule/update",
  projectByModules: "/projectmodule/project-modules",
  assignmentsAdd: "/assignments/add",
  assignmentsUpdate: "/assignments/update",
  assignmentsList: "/assignments/list",
  assignmentsDelete: "/assignments/delete",
  reportsAll: "/report/list",
  timesheetSummary: "/report/summary",
  clientAdd: "/clients/add",
  clientList: "/clients/list",
  clientDelete: "/clients/delete",
  clientUpdate: "/clients/update",
  updateClientStatus: "/clients/update-status",
  leaveList: "/leave/getallleaves",
  updateLeaveStatus: "/leave/update-status",
};

export default ApiRoutes;
